/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { EventsHelper, EventsHelperInterface } from "../EventsHelper";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "contract RetirementNFTAssociatedTicket",
        name: "retirementNFTAssociatedTicket",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "ticketTypes",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "mintAmounts",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "contract IRetirementNFT",
        name: "retirementNFT",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "uri",
        type: "string",
      },
    ],
    name: "BatchRetirementNFTAssociatedTicketMinted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "contract RetirementNFTAssociatedTicket",
        name: "retirementNFTAssociatedTicket",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "ticketType",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "mintAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "contract IRetirementNFT",
        name: "retirementNFT",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "uri",
        type: "string",
      },
    ],
    name: "RetirementNFTAssociatedTicketMinted",
    type: "event",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220029adccbfb004a707f7758203bd8aa216aac268b786d2bb090279a24c97b1a1064736f6c63430008070033";

type EventsHelperConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EventsHelperConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EventsHelper__factory extends ContractFactory {
  constructor(...args: EventsHelperConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "EventsHelper";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<EventsHelper> {
    return super.deploy(overrides || {}) as Promise<EventsHelper>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): EventsHelper {
    return super.attach(address) as EventsHelper;
  }
  connect(signer: Signer): EventsHelper__factory {
    return super.connect(signer) as EventsHelper__factory;
  }
  static readonly contractName: "EventsHelper";
  public readonly contractName: "EventsHelper";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EventsHelperInterface {
    return new utils.Interface(_abi) as EventsHelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EventsHelper {
    return new Contract(address, _abi, signerOrProvider) as EventsHelper;
  }
}
