/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRetirementNFTAssociatedTicketFactory,
  IRetirementNFTAssociatedTicketFactoryInterface,
} from "../IRetirementNFTAssociatedTicketFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "ticketTypes",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "mintAmounts",
        type: "uint256[]",
      },
      {
        internalType: "contract IRetirementNFT",
        name: "retirementNFT",
        type: "address",
      },
      {
        internalType: "string",
        name: "uri",
        type: "string",
      },
    ],
    name: "mintBatchRetirementNFTAssociatedTicket",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "ticketType",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "mintAmount",
        type: "uint256",
      },
      {
        internalType: "contract IRetirementNFT",
        name: "retirementNFT",
        type: "address",
      },
      {
        internalType: "string",
        name: "uri",
        type: "string",
      },
    ],
    name: "mintRetirementNFTAssociatedTicket",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRetirementNFTAssociatedTicketFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IRetirementNFTAssociatedTicketFactoryInterface {
    return new utils.Interface(
      _abi
    ) as IRetirementNFTAssociatedTicketFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRetirementNFTAssociatedTicketFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IRetirementNFTAssociatedTicketFactory;
  }
}
