/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRetirementNFTAssociatedTicket,
  IRetirementNFTAssociatedTicketInterface,
} from "../IRetirementNFTAssociatedTicket";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "ticketType",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "mintAmount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "ticketTypes",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "mintAmounts",
        type: "uint256[]",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "mintBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IRetirementNFT",
        name: "retirementNFT",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "randomNumber",
        type: "uint256",
      },
    ],
    name: "saveRetirementNFTAssociatedTicketMetadata",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRetirementNFTAssociatedTicket__factory {
  static readonly abi = _abi;
  static createInterface(): IRetirementNFTAssociatedTicketInterface {
    return new utils.Interface(_abi) as IRetirementNFTAssociatedTicketInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRetirementNFTAssociatedTicket {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IRetirementNFTAssociatedTicket;
  }
}
