/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRetirementNFTBundledTicket,
  IRetirementNFTBundledTicketInterface,
} from "../IRetirementNFTBundledTicket";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "contract IRetirementNFT",
        name: "retirementNFT",
        type: "address",
      },
    ],
    name: "mintNewRetirementNFTBundledTicket",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRetirementNFTBundledTicket__factory {
  static readonly abi = _abi;
  static createInterface(): IRetirementNFTBundledTicketInterface {
    return new utils.Interface(_abi) as IRetirementNFTBundledTicketInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRetirementNFTBundledTicket {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IRetirementNFTBundledTicket;
  }
}
