/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ITicketManagerFactory,
  ITicketManagerFactoryInterface,
} from "../ITicketManagerFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "contract ITicketManager",
        name: "ticketManager",
        type: "address",
      },
      {
        indexed: false,
        internalType: "contract IRetirementCertificateNFTAssociatedTicket",
        name: "retirementCertificateNFTAssociatedTicket",
        type: "address",
      },
    ],
    name: "TicketManagerCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "contract IRetirementCertificateNFTAssociatedTicket",
        name: "_retirementCertificateNFTAssociatedTicket",
        type: "address",
      },
    ],
    name: "createTicketManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITicketManagerFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ITicketManagerFactoryInterface {
    return new utils.Interface(_abi) as ITicketManagerFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITicketManagerFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ITicketManagerFactory;
  }
}
