/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, BigNumber, Signer, utils } from "ethers";
import { EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface EventsInterface extends utils.Interface {
  contractName: "Events";
  functions: {};

  events: {
    "BatchRetirementNFTAssociatedTicketMinted(address,address,uint256[],uint256[],address,string)": EventFragment;
    "RetirementNFTAssociatedTicketMinted(address,address,uint256,uint256,address,string)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "BatchRetirementNFTAssociatedTicketMinted"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "RetirementNFTAssociatedTicketMinted"
  ): EventFragment;
}

export type BatchRetirementNFTAssociatedTicketMintedEvent = TypedEvent<
  [string, string, BigNumber[], BigNumber[], string, string],
  {
    retirementNFTAssociatedTicket: string;
    to: string;
    ticketTypes: BigNumber[];
    mintAmounts: BigNumber[];
    retirementNFT: string;
    uri: string;
  }
>;

export type BatchRetirementNFTAssociatedTicketMintedEventFilter =
  TypedEventFilter<BatchRetirementNFTAssociatedTicketMintedEvent>;

export type RetirementNFTAssociatedTicketMintedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, string, string],
  {
    retirementNFTAssociatedTicket: string;
    to: string;
    ticketType: BigNumber;
    mintAmount: BigNumber;
    retirementNFT: string;
    uri: string;
  }
>;

export type RetirementNFTAssociatedTicketMintedEventFilter =
  TypedEventFilter<RetirementNFTAssociatedTicketMintedEvent>;

export interface Events extends BaseContract {
  contractName: "Events";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EventsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "BatchRetirementNFTAssociatedTicketMinted(address,address,uint256[],uint256[],address,string)"(
      retirementNFTAssociatedTicket?: null,
      to?: null,
      ticketTypes?: null,
      mintAmounts?: null,
      retirementNFT?: null,
      uri?: null
    ): BatchRetirementNFTAssociatedTicketMintedEventFilter;
    BatchRetirementNFTAssociatedTicketMinted(
      retirementNFTAssociatedTicket?: null,
      to?: null,
      ticketTypes?: null,
      mintAmounts?: null,
      retirementNFT?: null,
      uri?: null
    ): BatchRetirementNFTAssociatedTicketMintedEventFilter;

    "RetirementNFTAssociatedTicketMinted(address,address,uint256,uint256,address,string)"(
      retirementNFTAssociatedTicket?: null,
      to?: null,
      ticketType?: null,
      mintAmount?: null,
      retirementNFT?: null,
      uri?: null
    ): RetirementNFTAssociatedTicketMintedEventFilter;
    RetirementNFTAssociatedTicketMinted(
      retirementNFTAssociatedTicket?: null,
      to?: null,
      ticketType?: null,
      mintAmount?: null,
      retirementNFT?: null,
      uri?: null
    ): RetirementNFTAssociatedTicketMintedEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
