/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace DataTypes {
  export type RetirementNFTAssociatedTicketMetadataStruct = {
    ticketHolder: string;
    randomNumber: BigNumberish;
  };

  export type RetirementNFTAssociatedTicketMetadataStructOutput = [
    string,
    BigNumber
  ] & { ticketHolder: string; randomNumber: BigNumber };
}

export interface IRetirementNFTAssociatedTicketInterface
  extends utils.Interface {
  contractName: "IRetirementNFTAssociatedTicket";
  functions: {
    "getRetirementNFTAssociatedTicketMetadata(address)": FunctionFragment;
    "mint(address,uint256,uint256,bytes)": FunctionFragment;
    "mintBatch(address,uint256[],uint256[],bytes)": FunctionFragment;
    "saveRetirementNFTAssociatedTicketMetadata(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getRetirementNFTAssociatedTicketMetadata",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintBatch",
    values: [string, BigNumberish[], BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "saveRetirementNFTAssociatedTicketMetadata",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getRetirementNFTAssociatedTicketMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintBatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "saveRetirementNFTAssociatedTicketMetadata",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IRetirementNFTAssociatedTicket extends BaseContract {
  contractName: "IRetirementNFTAssociatedTicket";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRetirementNFTAssociatedTicketInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getRetirementNFTAssociatedTicketMetadata(
      retirementNFT: string,
      overrides?: CallOverrides
    ): Promise<
      [DataTypes.RetirementNFTAssociatedTicketMetadataStructOutput] & {
        _retirementNFTAssociatedTicketMetadata: DataTypes.RetirementNFTAssociatedTicketMetadataStructOutput;
      }
    >;

    mint(
      to: string,
      ticketType: BigNumberish,
      mintAmount: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mintBatch(
      to: string,
      ticketTypes: BigNumberish[],
      mintAmounts: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    saveRetirementNFTAssociatedTicketMetadata(
      retirementNFT: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getRetirementNFTAssociatedTicketMetadata(
    retirementNFT: string,
    overrides?: CallOverrides
  ): Promise<DataTypes.RetirementNFTAssociatedTicketMetadataStructOutput>;

  mint(
    to: string,
    ticketType: BigNumberish,
    mintAmount: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mintBatch(
    to: string,
    ticketTypes: BigNumberish[],
    mintAmounts: BigNumberish[],
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  saveRetirementNFTAssociatedTicketMetadata(
    retirementNFT: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getRetirementNFTAssociatedTicketMetadata(
      retirementNFT: string,
      overrides?: CallOverrides
    ): Promise<DataTypes.RetirementNFTAssociatedTicketMetadataStructOutput>;

    mint(
      to: string,
      ticketType: BigNumberish,
      mintAmount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    mintBatch(
      to: string,
      ticketTypes: BigNumberish[],
      mintAmounts: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    saveRetirementNFTAssociatedTicketMetadata(
      retirementNFT: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getRetirementNFTAssociatedTicketMetadata(
      retirementNFT: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mint(
      to: string,
      ticketType: BigNumberish,
      mintAmount: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mintBatch(
      to: string,
      ticketTypes: BigNumberish[],
      mintAmounts: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    saveRetirementNFTAssociatedTicketMetadata(
      retirementNFT: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getRetirementNFTAssociatedTicketMetadata(
      retirementNFT: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mint(
      to: string,
      ticketType: BigNumberish,
      mintAmount: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mintBatch(
      to: string,
      ticketTypes: BigNumberish[],
      mintAmounts: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    saveRetirementNFTAssociatedTicketMetadata(
      retirementNFT: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
