/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IRetirementNFTAssociatedTicketInterface
  extends utils.Interface {
  contractName: "IRetirementNFTAssociatedTicket";
  functions: {
    "mintNewRetirementNFTAssociatedTicket(address,uint256,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "mintNewRetirementNFTAssociatedTicket",
    values: [string, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "mintNewRetirementNFTAssociatedTicket",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IRetirementNFTAssociatedTicket extends BaseContract {
  contractName: "IRetirementNFTAssociatedTicket";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRetirementNFTAssociatedTicketInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    mintNewRetirementNFTAssociatedTicket(
      to: string,
      tokenId: BigNumberish,
      retirementNFT: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  mintNewRetirementNFTAssociatedTicket(
    to: string,
    tokenId: BigNumberish,
    retirementNFT: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    mintNewRetirementNFTAssociatedTicket(
      to: string,
      tokenId: BigNumberish,
      retirementNFT: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    mintNewRetirementNFTAssociatedTicket(
      to: string,
      tokenId: BigNumberish,
      retirementNFT: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    mintNewRetirementNFTAssociatedTicket(
      to: string,
      tokenId: BigNumberish,
      retirementNFT: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
