/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IRetirementNFTAssociatedTicketFactoryInterface
  extends utils.Interface {
  contractName: "IRetirementNFTAssociatedTicketFactory";
  functions: {
    "mintBatchRetirementNFTAssociatedTicket(address,uint256[],uint256[],address,string)": FunctionFragment;
    "mintRetirementNFTAssociatedTicket(address,uint256,uint256,address,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "mintBatchRetirementNFTAssociatedTicket",
    values: [string, BigNumberish[], BigNumberish[], string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintRetirementNFTAssociatedTicket",
    values: [string, BigNumberish, BigNumberish, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "mintBatchRetirementNFTAssociatedTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintRetirementNFTAssociatedTicket",
    data: BytesLike
  ): Result;

  events: {
    "BatchRetirementNFTAssociatedTicketMinted(address,address,uint256[],uint256[],address,string)": EventFragment;
    "RetirementNFTAssociatedTicketMinted(address,address,uint256,uint256,address,string)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "BatchRetirementNFTAssociatedTicketMinted"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "RetirementNFTAssociatedTicketMinted"
  ): EventFragment;
}

export type BatchRetirementNFTAssociatedTicketMintedEvent = TypedEvent<
  [string, string, BigNumber[], BigNumber[], string, string],
  {
    retirementNFTAssociatedTicket: string;
    to: string;
    ticketTypes: BigNumber[];
    mintAmounts: BigNumber[];
    retirementNFT: string;
    uri: string;
  }
>;

export type BatchRetirementNFTAssociatedTicketMintedEventFilter =
  TypedEventFilter<BatchRetirementNFTAssociatedTicketMintedEvent>;

export type RetirementNFTAssociatedTicketMintedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, string, string],
  {
    retirementNFTAssociatedTicket: string;
    to: string;
    ticketType: BigNumber;
    mintAmount: BigNumber;
    retirementNFT: string;
    uri: string;
  }
>;

export type RetirementNFTAssociatedTicketMintedEventFilter =
  TypedEventFilter<RetirementNFTAssociatedTicketMintedEvent>;

export interface IRetirementNFTAssociatedTicketFactory extends BaseContract {
  contractName: "IRetirementNFTAssociatedTicketFactory";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRetirementNFTAssociatedTicketFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    mintBatchRetirementNFTAssociatedTicket(
      to: string,
      ticketTypes: BigNumberish[],
      mintAmounts: BigNumberish[],
      retirementNFT: string,
      uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mintRetirementNFTAssociatedTicket(
      to: string,
      ticketType: BigNumberish,
      mintAmount: BigNumberish,
      retirementNFT: string,
      uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  mintBatchRetirementNFTAssociatedTicket(
    to: string,
    ticketTypes: BigNumberish[],
    mintAmounts: BigNumberish[],
    retirementNFT: string,
    uri: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mintRetirementNFTAssociatedTicket(
    to: string,
    ticketType: BigNumberish,
    mintAmount: BigNumberish,
    retirementNFT: string,
    uri: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    mintBatchRetirementNFTAssociatedTicket(
      to: string,
      ticketTypes: BigNumberish[],
      mintAmounts: BigNumberish[],
      retirementNFT: string,
      uri: string,
      overrides?: CallOverrides
    ): Promise<void>;

    mintRetirementNFTAssociatedTicket(
      to: string,
      ticketType: BigNumberish,
      mintAmount: BigNumberish,
      retirementNFT: string,
      uri: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BatchRetirementNFTAssociatedTicketMinted(address,address,uint256[],uint256[],address,string)"(
      retirementNFTAssociatedTicket?: null,
      to?: null,
      ticketTypes?: null,
      mintAmounts?: null,
      retirementNFT?: null,
      uri?: null
    ): BatchRetirementNFTAssociatedTicketMintedEventFilter;
    BatchRetirementNFTAssociatedTicketMinted(
      retirementNFTAssociatedTicket?: null,
      to?: null,
      ticketTypes?: null,
      mintAmounts?: null,
      retirementNFT?: null,
      uri?: null
    ): BatchRetirementNFTAssociatedTicketMintedEventFilter;

    "RetirementNFTAssociatedTicketMinted(address,address,uint256,uint256,address,string)"(
      retirementNFTAssociatedTicket?: null,
      to?: null,
      ticketType?: null,
      mintAmount?: null,
      retirementNFT?: null,
      uri?: null
    ): RetirementNFTAssociatedTicketMintedEventFilter;
    RetirementNFTAssociatedTicketMinted(
      retirementNFTAssociatedTicket?: null,
      to?: null,
      ticketType?: null,
      mintAmount?: null,
      retirementNFT?: null,
      uri?: null
    ): RetirementNFTAssociatedTicketMintedEventFilter;
  };

  estimateGas: {
    mintBatchRetirementNFTAssociatedTicket(
      to: string,
      ticketTypes: BigNumberish[],
      mintAmounts: BigNumberish[],
      retirementNFT: string,
      uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mintRetirementNFTAssociatedTicket(
      to: string,
      ticketType: BigNumberish,
      mintAmount: BigNumberish,
      retirementNFT: string,
      uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    mintBatchRetirementNFTAssociatedTicket(
      to: string,
      ticketTypes: BigNumberish[],
      mintAmounts: BigNumberish[],
      retirementNFT: string,
      uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mintRetirementNFTAssociatedTicket(
      to: string,
      ticketType: BigNumberish,
      mintAmount: BigNumberish,
      retirementNFT: string,
      uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
