/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IRetirementNFTInterface extends utils.Interface {
  contractName: "IRetirementNFT";
  functions: {
    "mintNewRetirementNFT(address,uint256)": FunctionFragment;
    "retirementNFTBalanceOf(address)": FunctionFragment;
    "retirementNFTOwnerOf(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "mintNewRetirementNFT",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "retirementNFTBalanceOf",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "retirementNFTOwnerOf",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "mintNewRetirementNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retirementNFTBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retirementNFTOwnerOf",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IRetirementNFT extends BaseContract {
  contractName: "IRetirementNFT";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRetirementNFTInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    mintNewRetirementNFT(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    retirementNFTBalanceOf(
      walletAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _balance: BigNumber }>;

    retirementNFTOwnerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { _owner: string }>;
  };

  mintNewRetirementNFT(
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  retirementNFTBalanceOf(
    walletAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  retirementNFTOwnerOf(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    mintNewRetirementNFT(
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    retirementNFTBalanceOf(
      walletAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    retirementNFTOwnerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    mintNewRetirementNFT(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    retirementNFTBalanceOf(
      walletAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    retirementNFTOwnerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    mintNewRetirementNFT(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    retirementNFTBalanceOf(
      walletAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    retirementNFTOwnerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
