/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IRetirementCertificateNFTInterface extends utils.Interface {
  contractName: "IRetirementCertificateNFT";
  functions: {
    "mintNewRetirementCertificateNFT(address,uint256)": FunctionFragment;
    "retirementCertificateNFTBalanceOf(address)": FunctionFragment;
    "retirementCertificateNFTOwnerOf(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "mintNewRetirementCertificateNFT",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "retirementCertificateNFTBalanceOf",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "retirementCertificateNFTOwnerOf",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "mintNewRetirementCertificateNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retirementCertificateNFTBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retirementCertificateNFTOwnerOf",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IRetirementCertificateNFT extends BaseContract {
  contractName: "IRetirementCertificateNFT";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRetirementCertificateNFTInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    mintNewRetirementCertificateNFT(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    retirementCertificateNFTBalanceOf(
      walletAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _numberOfRetirementNFTs: BigNumber }>;

    retirementCertificateNFTOwnerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { _owner: string }>;
  };

  mintNewRetirementCertificateNFT(
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  retirementCertificateNFTBalanceOf(
    walletAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  retirementCertificateNFTOwnerOf(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    mintNewRetirementCertificateNFT(
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    retirementCertificateNFTBalanceOf(
      walletAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    retirementCertificateNFTOwnerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    mintNewRetirementCertificateNFT(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    retirementCertificateNFTBalanceOf(
      walletAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    retirementCertificateNFTOwnerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    mintNewRetirementCertificateNFT(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    retirementCertificateNFTBalanceOf(
      walletAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    retirementCertificateNFTOwnerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
