/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface MockRetirementNFTAssociatedTicketGatedServiceInterface
  extends utils.Interface {
  contractName: "MockRetirementNFTAssociatedTicketGatedService";
  functions: {
    "accessSpecialContent()": FunctionFragment;
    "verifyRetirementNFTAssociatedTicket()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "accessSpecialContent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyRetirementNFTAssociatedTicket",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "accessSpecialContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyRetirementNFTAssociatedTicket",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MockRetirementNFTAssociatedTicketGatedService
  extends BaseContract {
  contractName: "MockRetirementNFTAssociatedTicketGatedService";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockRetirementNFTAssociatedTicketGatedServiceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    accessSpecialContent(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    verifyRetirementNFTAssociatedTicket(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  accessSpecialContent(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  verifyRetirementNFTAssociatedTicket(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    accessSpecialContent(overrides?: CallOverrides): Promise<boolean>;

    verifyRetirementNFTAssociatedTicket(
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    accessSpecialContent(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    verifyRetirementNFTAssociatedTicket(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    accessSpecialContent(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    verifyRetirementNFTAssociatedTicket(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
